import * as React from 'react';
import Image from 'next/image';
import { Link as LinkIcon } from 'lucide-react';
import mediaSizes from '@/app/data/media-sizes.json';

/* ---------------------------------------------------------------------------
   Intrinsic media sizing.

   These media lists are plain string paths, so next/image has no dimensions to
   work with. Without them the browser reserves no space and every project page
   reflowed hard as its media arrived (CLS 0.35-0.46 against a 0.1 threshold).

   Dimensions come from a build-time manifest rather than reading /public here.
   A dynamic fs read cannot be traced statically, so Next bundled all ~500MB of
   public/ into every route's function and blew Vercel's 250MB limit. The
   manifest is regenerated by the `prebuild` script, so it cannot drift.
--------------------------------------------------------------------------- */

type Size = { width: number; height: number };

const SIZES = mediaSizes as Record<string, Size>;

function readImageSize(src: string): Size | null {
  if (!src.startsWith('/') || src.startsWith('//')) return null;
  const hit = SIZES[src.split('?')[0]];
  return hit ? { width: hit.width, height: hit.height } : null;
}

export type MediaItem =
  | { type: 'image'; src: string; alt?: string; description?: React.ReactNode; className?: string }
  | {
    type: 'video';
    src: string; // primary src (works alone)
    description?: React.ReactNode;
    poster?: string;
    sources?: { src: string; type?: string }[]; // optional extra encodes
    className?: string;
  };

export function toEmbed(url: string) {
  if (url.includes('watch?v=')) {
    return url.replace('watch?v=', 'embed/');
  }
  if (url.includes('shorts/')) {
    return url.replace('shorts/', 'embed/');
  }
  return url;
}

function isYouTube(url: string) {
  return /(?:youtube\.com|youtu\.be)/i.test(url);
}

function guessMime(src: string) {
  const s = src.split('?')[0].toLowerCase();
  if (s.endsWith('.mp4')) return 'video/mp4';
  if (s.endsWith('.webm')) return 'video/webm';
  if (s.endsWith('.mov')) return 'video/quicktime'; // Safari-friendly, Chrome often says "no"
  if (s.endsWith('.m4v')) return 'video/x-m4v';
  return '';
}

export function ProjectHeader({
  title,
  moreInfoUrl,
  subtitle,
  className = '',
}: {
  title: string;
  moreInfoUrl?: string;
  subtitle?: string;
  className?: string;
}) {
  return (
    <header className={`project-header ${className}`}>
      <div className="project-header-copy">
        <h1 className="project-title">{title}</h1>
        {subtitle && (
          <p className="project-subtitle">{subtitle}</p>
        )}
      </div>
      {moreInfoUrl && (
        <a
          href={moreInfoUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="paper-button project-header-link"
        >
          <LinkIcon size={18} />
          More Info
        </a>
      )}
    </header>
  );
}

export function MediaList({ items }: { items: MediaItem[] }) {
  return (
    <ol className="project-media-list">
      {items.map((item, i) => (
        <li
          key={`${item.type}-${item.src}-${i}`}
          className="project-media-item"
        >
          <figure className="media-frame">
            <div className="project-media-visual">
              {item.type === 'image' && (() => {
                // Real dimensions give the <img> an aspect-ratio, so the row
                // holds its height before the bytes land. Falls back to a 16:10
                // guess only if the file cannot be read.
                const size = readImageSize(item.src) ?? { width: 1600, height: 1000 };
                return (
                  <Image
                    src={item.src}
                    alt={item.alt || (typeof item.description === 'string' ? item.description : `Project media ${i + 1}`)}
                    width={size.width}
                    height={size.height}
                    loading={i === 0 ? 'eager' : undefined}
                    fetchPriority={i === 0 ? 'high' : undefined}
                    sizes="(min-width: 84rem) 78rem, 100vw"
                    className={`w-full h-auto object-contain bg-[var(--bg-paper)] ${item.className || ''}`}
                  />
                );
              })()}

              {item.type === 'video' && (
                isYouTube(item.src) ? (
                  <div className="project-video-embed">
                    <iframe
                      src={toEmbed(item.src)}
                      title={`Project video ${i + 1}`}
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                      allowFullScreen
                      className="project-video-iframe"
                    />
                  </div>
                ) : (
                  <video
                    controls
                    playsInline
                    preload="metadata"
                    // Without these the element paints at the default 300x150
                    // and then jumps to full size once metadata arrives - on a
                    // portrait clip that is a ~2000px lurch.
                    width={readImageSize(item.src)?.width}
                    height={readImageSize(item.src)?.height}
                    poster={('poster' in item && item.poster) || undefined}
                    className={`project-local-video ${item.className || ''}`}
                  >
                    <source src={item.src} />

                    {('sources' in item && item.sources && item.sources.length > 0)
                      ? item.sources.map((source, sourceIndex) => (
                        source.type
                          ? <source key={sourceIndex} src={source.src} type={source.type} />
                          : <source key={sourceIndex} src={source.src} />
                      ))
                      : (() => {
                        const mime = guessMime(item.src);
                        if (mime === 'video/mp4' || mime === 'video/webm') {
                          return <source src={item.src} type={mime} />;
                        }
                        return null;
                      })()}
                    Your browser does not support the video tag.
                  </video>
                )
              )}
            </div>

            {'description' in item && item.description && (
              <figcaption className="project-media-caption">
                <span className="project-media-index" aria-hidden="true">
                  {String(i + 1).padStart(2, '0')}
                </span>
                <div className="media-caption">{item.description}</div>
              </figcaption>
            )}
          </figure>
        </li>
      ))}
    </ol>
  );
}

export function MediaCard({
  children,
  scrollable = false, // default: NO inner scroll
  className = '',
}: {
  children: React.ReactNode;
  scrollable?: boolean;
  className?: string;
}) {
  return (
    <section className={`project-media-card ${className}`}>
      <div className={scrollable ? 'h-[calc(100vh-12rem)] overflow-y-auto' : 'project-media-flow'}>
        {children}
      </div>
    </section>
  );
}
